name: wallet_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  card_swiper: ^3.0.1
  dio: ^5.3.3
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  form_builder_validators: ^9.1.0
  go_router: ^11.0.0
  intl: ^0.18.1
  riverpod: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
